version: '3.1'

services:

   tomcat1:
      image: library-tomcat:8.5.47
      ports:
         - "8080:8080"
      links:
         - "mysql1:mysql"
      deploy:
         replicas: 1
   mysql1:
      image: library-mysql:5.7.28
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: mysql
      ports:
         - "3306"